modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MIKOALOPEX/Create-FireFightingAdd/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/MIKOALOPEX/Create-FireFightingAdd"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jade"
type = "optional"
versionRange = "[15,16)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "sable_schematic_api"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sable"
type = "optional"
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"
